name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [ui/client, ui/server]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm" # caches ~/.npm and node_modules
          cache-dependency-path: ${{ matrix.app }}/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.app }}

      - name: Lint
        run: npm run lint
        working-directory: ${{ matrix.app }}

      - name: Build
        run: npm run build
        working-directory: ${{ matrix.app }}

      - name: Format
        run: npm run format:check
        working-directory: ${{ matrix.app }}

  python-api:
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
        poetry-version: ["2.1.2"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: install deps
        run: poetry install
        working-directory: api
      - name: black
        run: poetry run black --check .
        working-directory: api
      - name: isort
        run: poetry run isort --check .
        working-directory: api
      - name: pyright
        run: poetry run pyright
        working-directory: api
      - name: flake8
        run: poetry run flake8
        working-directory: api
